
attacking_metrics = ['xG', 'opxG', 'npxG', 'Gol', 'xOVA', 'xT']#, 'xT_from_carries']  # 'xg_against_team']

shots = ['Tiri', 'Tiri da area', 'Tiri da area piccola', 'Tiri fuori area',
          'Tiri in porta']
#'Tiri in porta subiti'
#'Tiri di testa'
# 'Tiri di rigore'
#'Tiri su Promettente'
spreads = ['Gol-xG']

passing_metrics = [
    'xA',
    'xT_from_passes',
    'Passaggi Chiave',
    'Passaggi Chiave ricevuti',
    'Assist',
    'Assist Vincenti',
    'Triangolazioni',
    'Cross riusciti',
    'Traversoni riusciti',
    'Cut Back riusciti'
]

physical_metrics = [
    'HSR Distance',
    'Sprinting Distance',
    'HI Distance',
    'PSV-99',
    'Count High Acceleration',
    'Count High Deceleration',
    'Count HSR',
    'Count Sprint',
    'Count HI'
]
defensive_metrics = [
    'Duelli di gioco',
    'Duelli vinti',
    'Duelli tackle',
    'Duelli tackle vinti',
    'Duelli aerei',
    'Duelli aerei vinti',
    'Duelli nella metà campo offensiva',
    'Duelli vinti nella metà campo offensiva',
    'Interventi decisivi +'
]

offensive_events = ['Rete Fatta', 'Tiro Fatto']
defensive_events = ['Intervento  Decisivo',
                    'Duello Vinto']#, 'Recupera Palla', 'Rete Subita']

defensive_markers = {
    'Rete Subita': '*',
    'Tiro Subito': '.'
}

numeric_fields = ['touches',
                   'xG',
                   'npxG',
                   'opxG',
                   'xA',
                   'opxA',
                   'xOVA',
                   'xA_received',
                   'xT',
                   'xT_from_passes',
                   'xT_from_carries',
                   'xT_from_passes_received',
                   'xg_blocked',
                   'xg_against_team',
                   'Tiri',
                   'Tiri in porta',
                   'Tiri da area',
                   'Tiri da area piccola',
                   'Tiri fuori area',
                   'Tiri di testa',
                   'Tiri di rigore',
                   'Gol',
                   'Gol da area',
                   'Gol da area piccola',
                   'Gol fuori area',
                   'Gol di testa',
                   'Gol di piede',
                   'Gol su PI',
                   'Gol su Pun. Centrale',
                   'Gol su Pun. Laterale',
                   'Gol su Corner',
                   'Gol su Rimessa',
                   'Gol su rigore',
                   'Gol su sviluppo rigore',
                   'Gol su Pun. Diretta',
                   'Gol su sviluppo Pun. Diretta',
                   'Tiri su Occasione Gol',
                   'Realizzazione su Occasione Gol',
                   'Tiri su Promettente',
                   'Realizzazione su Promettente',
                   'Passaggi Chiave',
                   'Passaggi Chiave in area',
                   'Passaggi Chiave ricevuti',
                   'Passaggi Chiave ricevuti in area',
                   'Assist',
                   'Assist Vincenti',
                   'Assist in area',
                   'Assist Vincenti in area',
                   'Third pass',
                   'Third pass vincenti',
                   'Gol procurati',
                   'Triangolazioni',
                   'Triangolazioni fatte',
                   'Triangolazioni chiuse',
                   'lanci/passaggi portiere ricevuti',
                   'lanci/passaggi portiere ricevuti campo off.',
                   'Passaggi',
                   '% Passaggi riusciti',
                   'Passaggi ricevuti',
                   'Palle Laterali',
                   'Cross',
                   'Cross riusciti',
                   '% Cross riusciti',
                   'Cross vincenti',
                   '% Cross vincenti',
                   'Traversoni',
                   'Traversoni riusciti',
                   '% Traversoni riusciti',
                   'Traversoni vincenti',
                   '% Traversoni vincenti',
                   'Cut Back',
                   'Cut Back riusciti',
                   '% Cut Back riusciti',
                   'Cut Back vincenti',
                   '% Cut Back vincenti',
                   'Perde palla',
                   'Propria metà campo',
                   'Recupera palla',
                   'Metà campo avversaria',
                   'H media recupera palla (no P)',
                   'Dribbling',
                   'Dribbling vincenti',
                   '% dribbling vincenti',
                   'Dribbling subiti',
                   'Dribbling perdenti subiti',
                   '% dribbling perdenti subiti',
                   'Duelli',
                   'Duelli di gioco',
                   'Duelli vinti',
                   '% duelli vinti',
                   'Duelli nella metà campo offensiva',
                   'Duelli vinti nella metà campo offensiva',
                   '% duelli vinti nella metà campo offensiva',
                   'Duelli aerei',
                   'Duelli aerei vinti',
                   '% duelli arei vinti',
                   'Duelli tackle',
                   'Duelli tackle vinti',
                   '% duelli tackle vinti',
                   'Interventi decisivi +',
                   'Interventi decisivi -',
                   'Reti subite squadra',
                   'Minuti giocati / gol subiti',
                   'Falli fatti',
                   'Falli subiti',
                   'H media falli (m)',
                   'In Fuorigioco',
                   'Ammonizioni',
                   'Espulsioni',
                   'Doppie Ammonizioni',
                   'Parate',
                   'Gol subiti',
                   'Uscite',
                   'Tiri in porta subiti',
                   '% parate su tiri in porta subiti',
                   'Rigori',
                   'Rigori parati',
                   'Interventi decisivi +2',
                   'Interventi decisivi -3',
                   'Passaggi portiere',
                   'Passaggi portiere +',
                   '% passaggi +',
                   '% passaggi su gioco portiere',
                   'Lanci',
                   'Lanci +',
                   '% lanci +',
                   '% lanci su gioco portiere',
                   'Minutes Played',
                   'Minutes Played TIP',
                   'Minutes Played OTIP',
                   'Player ID',
                   'Distance',
                   'M/min',
                   'Running Distance',
                   'HSR Distance',
                   'Sprinting Distance',
                   'HI Distance',
                   'Count HSR',
                   'Count Sprint',
                   'Count HI',
                   'Count Medium Acceleration',
                   'Count High Acceleration',
                   'Count Medium Deceleration',
                   'Count High Deceleration',
                   'PSV-99',
                   'Distance TIP',
                   'M/min TIP',
                   'Running Distance TIP',
                   'HSR Distance TIP',
                   'Sprinting Distance TIP',
                   'HI Distance TIP',
                   'Count HSR TIP',
                   'Count Sprint TIP',
                   'Count HI TIP',
                   'Count Medium Acceleration TIP',
                   'Count High Acceleration TIP',
                   'Count Medium Deceleration TIP',
                   'Count High Deceleration TIP',
                   'Distance OTIP',
                   'M/min OTIP',
                   'Running Distance OTIP',
                   'HSR Distance OTIP',
                   'Sprinting Distance OTIP',
                   'HI Distance OTIP',
                   'Count HSR OTIP',
                   'Count Sprint OTIP',
                   'Count HI OTIP',
                   'Count Medium Acceleration OTIP',
                   'Count High Acceleration OTIP',
                   'Count Medium Deceleration OTIP',
                   'Count High Deceleration OTIP']
